name: tcsflutter_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_messaging: ^6.0.9
  hexcolor:
  curved_drawer: ^0.1.2
  video_player: ^2.1.3
  polygon_clipper: ^1.0.2
  firebase_core:  ^0.7.0
  firebase_auth: ^0.20.1
  firebase_database: ^6.0.0
  flutter_signin_button: ^1.1.0
  google_sign_in: ^4.5.1
  razorpay_flutter: ^1.1.4
  url_launcher: ^5.4.0
  carousel_slider: ^3.0.0
  dropdown_formfield: ^0.1.3
  webview_flutter: ^1.0.5
  quick_feedback: ^0.1.1
  flutter_email_sender: ^5.0.0
  image_picker: ^0.6.7+22
  mailto: ^2.0.0
  flutter_launcher_icons: ^0.9.0
  shared_preferences:
  font_awesome_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - attitude_smile_and_picture_perfect.jpg
    - Black_on_white_without_bg.png
    - collecting_memories.jpg
    - Dr.MukeshKumar(Mentor).jpg
    - forever_and_beyound.JPG
    - friends_forever.JPG
    - it_s_just_called_best.JPG
    - let_me_feel_the_breeze.JPG
    - our_merchandise_launch.jpg
    - sing_like_a_melody.jpg
    - smile_best_medicine_ever_made.JPG
    - the_boys_gang.JPG
    - the_girls_corner.jpg
    - the_party_peoples.jpg
    - tough_and_strong.jpg
    - we_represent_hand_together_forever.jpg
    - yes_i_am_childish.jpg
    - uk.png
    - greece.png
    - egypt.png
    - 5.jpg
    - 6.jpg
    - 7.jpg
    - 14.jpg
    - 19.jpg
    - M1.jpg
    - M2.jpg
    - M3.jpg
    - M4.jpg
    - M5.jpg
    - M6.jpg
    - M7.jpg
    - M8.jpg
    - M9.jpg
    - M10.jpg
    - M11.jpg
    - M12.jpg
    - M13.jpg
    - M14.jpg
    - M15.jpg
    - M17.jpg
    - M20.jpg
    - M21.jpg
    - M22.jpg
    - M23.jpg
    - M24.jpg
    - M25.jpg
    - M26.jpg
    - M27.jpg
    - M28.jpg
    - M29.jpg
    - M30.jpg
    - M31.jpg
    - M32.jpg
    - M33.jpg
    - M34.jpg
    - M35.jpg
    - M36.jpg
    - M37.jpg
    - M38.jpg
    - M39.jpg
    - M40.jpg
    - M41.jpg
    - M43.jpg
    - M44.jpg
    - M45.jpg
    - M46.jpg
    - M47.jpg
    - M48.jpg
    - M49.jpg
    - M50.jpg
    - M51.jpg
    - M52.jpg
    - M53.jpg
    - M54.jpg
    - M55.jpg
    - M56.jpg
    - M57.jpg
    - M58.jpg
    - M59.jpg
    - M60.jpg
    - M61.jpg
    - M62.jpg
    - M63.jpg
    - M64.jpg
    - M65.jpg
    - M_Abhilaksh.jpg
    - A1.jpg
    - A2.jpg
    - A3.jpg
    - A4.jpg
    - A5.jpg
    - A6.jpg
    - A7.jpg
    - A8.jpg
    - A9.jpg
    - A10.jpg
    - A11.jpg
    - A12.jpg
    - A13.jpg
    - A14.jpg
    - A15.jpg
    - A16.jpg
    - A17.jpg
    - A18.jpg
    - A19.jpg
    - A20.jpg
    - A21.jpg
    - Ms.ArchanaParmar.jpeg
    - claritus.png
    - cognizant.png
    - daffodilsw.png
    - infosys.png
    - naggaro.png
    - newgen.png
    - sapient.png
    - tcs.png
    - vvdn.png
    - logo.jpeg
    - undraw_flutter_dev_wvqj.png
    - undraw_project_team_lc5a.png
    - undraw_voice_interface_eckp.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

fonts:
    - family: OpenSans
      fonts:
        - asset: assets/font/FreightSans-Regular.ttf
        - asset: assets/font/FreightSans-Bold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/c